### ISSUE TITLE
Several feeds are deprecated or that have the wrong links

### ISSUE THREAD

**Issue by santosomar** [yeti-platform/yeti#591]
### Description
There are several feeds that are deprecated or that have the wrong links. 
For example:
```
ERROR updating feed: https://hosts-file.net/exp.txt returns code: 404
ERROR updating feed: https://hosts-file.net/psh.txt returns code: 404 
ERROR updating feed: https://malwareconfig.com/static/C2_All.csv returns code: 404
ERROR updating feed: http://data.phishtank.com/data/None/online-valid.csv returns code: 404
```
The correct PhishTank address is http://data.phishtank.com/data/online-valid.csv

### Environment
This is observed with the latest Yeti Docker container.

### Steps to Reproduce
Instantiate the supported docker container using docker-compose, as documented in this repository.

**Comment by h0n3yc4k3** [comment]
I have same problem

**Comment by GrandGamer** [comment]
I also have the same issue.

Specifically for phishtank, I use my API key in yeti.conf file but I still get the same error:
`[2020-09-25 15:41:34,614: ERROR/ForkPoolWorker-8] Traceback (most recent call last):
  File "/opt/yeti/core/feed.py", line 50, in update_feed
    f.update()
  File "/opt/yeti/plugins/feeds/public/phishtank.py", line 28, in update
    for index, line in self.update_csv(delimiter=',',
  File "/opt/yeti/core/feed.py", line 405, in update_csv
    r = self._make_request(
  File "/opt/yeti/core/feed.py", line 300, in _make_request
    raise GenericYetiError(
core.errors.GenericYetiError: http://data.phishtank.com/data/None/online-valid.csv returns code: 404
[2020-09-25 15:41:34,614: ERROR/ForkPoolWorker-8] ERROR updating feed: http://data.phishtank.com/data/None/online-valid.csv returns code: 404`

When I manually load the phishtank module from a python interactive shell, the object appears to load the key normally from the same config file. I even tried rebooting the entire system. Looks like the worker is not loading the correct yeti.conf file? maybe I need to put it somewhere else instead of /opt/yeti?

**Comment by sebdraven** [comment]
you have set the yeti.conf file ?

**Comment by GrandGamer** [comment]
> you have set the yeti.conf file ?

yes

**Comment by sebdraven** [comment]
Sorry for the delay, 

have yo got this problem yet ?

in the yeti.conf 

you add:

[phishtank]
key=<your_key>

For the feed of malwareconfig I delete the feed, it's not updated

**Comment by sebdraven** [comment]
I've just fixed deprecated fixed here. https://github.com/yeti-platform/yeti/commit/a3659a3264f196078b38b60f181de2cbbb55cb32 and https://github.com/yeti-platform/yeti/commit/6c67a91c197cdec68796dfd899a524e6fd1dd47d

**Comment by santosomar** [comment]
Excellent! Thank you so much!

**Comment by GrandGamer** [comment]
> 
> 
> Sorry for the delay,
> 
> have yo got this problem yet ?
> 
> in the yeti.conf
> 
> you add:
> 
> [phishtank]
> key=<your_key>
> 
> For the feed of malwareconfig I delete the feed, it's not updated

Sorry for the late reply. Yes I still have the same issue with phishtank. 

My /opt/yeti/yeti.conf file contains the following for phishtank(key hidden for obvious reasons):
```
[phishtank]
key=7e3fe...f04f
```

**Comment by sebdraven** [comment]
@GrandGamer ok i fixe the bug and I release the version 1.6. When you have installed the new version. You have to delete the entry feed in mongodb. For that

`mongodb
use yeti
db.schedule_entry.deleteOne({"name":"PhishTank"})
`

and it must work.

**Comment by GrandGamer** [comment]
I can confirm that it works now. Thank you very much!
